### PR TITLE
make python3 compatible

### PR DESCRIPTION
**Pull request by bernieke**
Just a few small changes were required to make the library python3 compatible.

### CODE REVIEW

**Comment by Bobspadger** [comment]
Thanks, just merged into my fork.

Much appreciated

**Comment by Bobspadger** [comment]
this does not work with HTTPS sites using python3 with homebrew.

I would get

```
[SSL: CERTIFICATE_VERIFY_FAILED

```

doing some digging it looks like you need to have openssl101

so

```
brew search openssl                                                                                                                                                         openssl
homebrew/versions/openssl098  homebrew/versions/openssl101

brew install homebrew/versions/openssl101

brew unlink openssl         

brew link openssl101 --force

```

which gets past the SSL error but now gives

```

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

```

any ideas ?

**Comment by bernieke** [comment]
I don't have a magento behind https available to test against.

I do remember having an issue with ssl in another project after the latest
2.7 update when the https site is self-signed, or otherwise non-verified,
which would also occur with python3. (It was a security backport.)

The solution for me then was:
  import ssl
  if hasattr(ssl, '_create_unverified_context'):
      ssl._create_default_https_context = ssl._create_unverified_context

If the problem is due to homebrew and/or the openssl library, I won't be of
any help. The last time I touched a mac they were still running on powerpc
:)

**Comment by Bobspadger** [comment]
cool, thanks for the reply

for your code 

```
import ssl
  if hasattr(ssl, '_create_unverified_context'):
      ssl._create_default_https_context = ssl._create_unverified_context
```

do I just put this in the the magento **init**.py file ? and it will over-ride the SSL contects (sorry I hate all the certificate stuff!)

I did have a similar problem with python2.7 but that was because our certificate chain was broken, but I've fixed this now. It might be that openSSL and the Chrome browser use different trusted root ?

**Comment by bernieke** [comment]
You can put it anywhere before the socket.connect happens.

But I wouldn't put it in the sources of python-magento, it basically turns
off the certificate checking. (Although they only got around to
implementing the check in python some two months ago...)

It would be up to the user to use the snippet, so if anywhere I'd just add
it to the documentation. If this is in fact the problem you're having, it's
not because of python-magento, it's python itself. (Or rather the
certificates on the host or on the server.)

And yes, I do think Chrome comes with its own set of certificates. The
system-wide ones are usually provided by a ca-certificates package, and can
be checked with wget. (wget would need the --no-check-certificate flag in
the same way python would need the ssl snippet.)

**Comment by Bobspadger** [comment]
hmmm wget is showing as

```
Unable to locally verify the issuer's authority.
```

**Comment by bernieke** [comment]
Good, so if the certificate is accepted by chrome, that means it's just the
host which is missing the mac/homebrew equivalent of ca-certificates.
Or there's still something wrong with the homebrew openssl python & wget
are compiled against.
Either way you're now pretty sure it's not the server, the certificate or
python-magento which is causing the problem :)

**Comment by Bobspadger** [comment]
looks like its something to do with my computer.

I've checked with rackspace and our certs are all good.

If I log on to other computers (ubuntu / raspberry pi) and do wget www.mydomain.co.uk I get certificate all ok and web page downloaded

If I do it from my mac (wget installed by homebrew) I get certificate errors.

Joy

Thanks for your help!

**Comment by Bobspadger** [comment]
Installed Python3 from the python website (not homebrew) and all is working as expected. No nasty over-rides!

Now we just need your conversion meged into the original repo!

**Comment by voberoi** [comment]
Hey @Bobspadger,

Thanks for doing this!

I am no longer maintaining this project (clearly). May I change my README to direct folks to your fork?

Vikram

**Comment by Bobspadger** [comment]
Hi 

Sure, feel free. I might suggest that @bernieke seems far more proficient in this than I do - maybe his would be best? If not, I'm happy to have it pointed to mine - I'm currently working with it on an almost daily basis now.

Cheers

Alex

**Comment by bernieke** [comment]
I don't mind taking over maintenance of the project, provided you can give
me the rights to publish to pypi as well? I'm bernieke <
bernieke@bernieke.com> over there too.

Greetings,
Bernard

**Comment by voberoi** [comment]
@bernieke and @Bobspadger,

Sorry this took so long.

@bernieke -- you'll notice I have your repo plastered on this repo's front page! Folks should be directed there, I will be ignored PRs and Issues opened against this repo.

@bernieke, I've also given you rights to publish to pypi. Feel free to remove me as an owner as well.

Thanks!

**Pull request closed without merging**
